services:
  mongodb_youtrack:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_youtrack:/data/db
    networks:
      - app-network

  mongodb_gitlab:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_gitlab:/data/db
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - MONGODB_URI_1=mongodb://mongodb_youtrack:27017/nest
      - MONGODB_URI_2=mongodb://mongodb_gitlab:27017/nest
    restart: always
    depends_on:
      - mongodb_youtrack
      - mongodb_gitlab
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: pnpm dev

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_youtrack:
  mongodb_gitlab:
